[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'cocopon/iceberg.vim'
hook_add = '''
    colorscheme iceberg
    syntax on
'''

[[plugins]]
repo = 'vim-airline/vim-airline'

[[plugins]]
repo = 'neoclide/coc.nvim'
rev = 'release'
build = 'coc#util#intall()'
hook_add = '''
    source ~/.config/nvim/plugins/coc.rc.vim
'''
